# Name of workflow
name: Check all URLs

# Run workflow once a week at 11:35pm
#on:
#  schedule:
#    - cron: '55 23 * * 0'
  # Run workflow on pushes to main branch
#  push:
#    branches:
#      - main

on:
  workflow_dispatch

# Steps to carry out
jobs:
  build:
    # Create a ubuntu virtual machine
    runs-on: ubuntu-latest

    # Checkout repo code
    steps:
    - name: Checkout repo
      uses: actions/checkout@v2

    # Install node
    - name: Use Node.js
      uses: actions/setup-node@v1
      with:
        node-version: 10.16
    - run: npm install
    - run: npm run build --if-present
    - run: npm test
      env:
        CI: true

    # Run script checkURLsinMarkdown.js
    # Show the results
    - name: Check URLs
      run: |-
        node checkURLsInMarkdown.js
        cat urlCheck.txt

    # Commit changes
    - name: Commit
      run: |-
        git config user.name github-actions
        git config user.email github-actions@github.com
        git add -f urlCheck.txt
        git commit -m "urlCheck file"
        git push
